---
deployment:
  tasks:
    - export DEPLOYPATH=/home/b913955/rprowashnc.com/
    - /bin/cp dist/index.html $DEPLOYPATH
    - /bin/cp dist/robots.txt $DEPLOYPATH
    - /bin/cp -R dist/_astro $DEPLOYPATH
    - /bin/cp -R dist/blog $DEPLOYPATH
    - /bin/cp -R dist/contact $DEPLOYPATH
    - /bin/cp -R dist/services $DEPLOYPATH
    - /bin/cp dist/sitemap-0.xml $DEPLOYPATH
    - /bin/cp dist/sitemap-index.xml $DEPLOYPATH